spring.application.name=rabqueues


server.port=8082
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

# SMTP Mail Configuration (e.g., Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



#spring.rabbitmq.username=guest
spring.rabbitmq.username=admin
spring.rabbitmq.password=secretpassword
#spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/

spring.rabbitmq.template.retry.enabled=true
spring.rabbitmq.template.retry.max-attempts=3
spring.rabbitmq.template.retry.initial-interval=1000
spring.rabbitmq.template.retry.max-interval=10000


spring.rabbitmq.listener.simple.default-requeue-rejected=false